version: '3.7'

services:
  postgres:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes:
      - ./docker-scripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - postgres_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
      - ${HASURA_PORT}:8080
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${HASURA_DATABASE}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_ENABLE_CONSOLE}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_AUTH_HOOK: http://host.docker.internal:8000/${HASURA_WEBHOOK}

  minio:
    image: minio/minio:latest
    volumes:
      - file_data:/data
      - minio_events:/events
    ports:
      - "${MINIO_PORT}:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

  keycloak:
    image: jboss/keycloak:6.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_DATABASE}
      DB_USER: ${POSTGRES_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/realm-export.json
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    volumes: 
      - ./server/realm-export.json:/opt/jboss/keycloak/realm-export.json
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - postgres
    restart: always
  
  redis:
    image: redis:alpine
    container_name: sessions
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./server/sessions:/sessions
    restart: always

  # dejavu:
  #   image: appbaseio/dejavu
  #   restart: unless-stopped
  #   networks:
  #     - search
  #   ports:
  #     - 1358:1358
  #   depends_on:
  #     - search

volumes:
  minio_events:
  postgres_data:
  file_data: