- model: User
  graph:
    - fullName: 'Jeffrey Spies'
      projects:
        - title: Project 1
          _isHidden: true
        - title: Project 2
        - title: Project 3
        - title: Project 4
- model: Group
  graph:
    - name: FirstGroup 
      isGenerated: true
      isIndividual: true
      users:
        - id: 1
- model: Permission
  graph:
    - groupId: 1
      assetId: 2
      type: read
    - groupId: 1
      assetId: 3
      type: read